---
title: "Conceptual Questions"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

1.  If your working directory is myfolder/homework/, what relative path would you specify to get the file located at myfolder/MyData.csv?

> ../MyData.csv

2.  What are the major benefits of using R projects?

> R projects organizes everything like settings, packages, environment so that we can easily share the project between multiple Operating Systems

3.  What is git and what is github?

> Git is a version control system that allows taking snapshots of files/projects and github is an online platform to store and mange such files/projects using git.

4.  What are the two main differences between a tibble and a data.frame?

> Data frame is a data structure in base R which store 2 dimensional data or tabular data.Tibble is a data structure in tidyverse package which internally uses data frame. Data frame always prints the whole table by default but tibble provides meaningful information of the table and print only 10 rows.

5.Rewrite the following nested function call using BaseR’s chaining operator:

arrange(filter(select(as_tibble(iris), starts_with("Petal"), Species), Petal.Length <
1.55), Species)


> as_tibble(iris) |>
select (starts_with ("Petal"), Species)
filter(petal.length < 1.55) |>
arrange (Species)




